server:
  port: 9020
spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 100MB
  jackson:
    default-property-inclusion: non_null
  application:
    name: spark-admin
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url:  jdbc:mysql://mysql.example.com:3306/spark-dev?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: 123456
    name: spark-dev
    type: com.alibaba.druid.pool.DruidDataSource
    initial-size: 5
    min-idle: 5
    max-active: 20
    max-wait: 30000
    time-between-eviction-runs-millis: 60000
    min-evictable-idle-time-millis: 300000
    validation-query: select '1' from dual
    test-while-idle: true
    test-on-borrow: false
    test-on-return: false
    pool-prepared-statements: true
    max-open-prepared-statements: 20
    max-pool-prepared-statement-per-connection-size: 20
    filters: stat,wall
  boot:
    admin:
      client:
        url: http://127.0.0.1:8980
        instance:
          prefer-ip: true
  redis:
    host: redis.example.com
    port: 6379
    timeout: 10000
    database: 0
    password:
    lettuce:
      pool:
        max-active: 300
        max-idle: 100
        max-wait: -1
        min-idle: 20
      shutdown-timeout: 10000
mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.spark.platform.adminapi.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    cache-enabled: false
    map-underscore-to-camel-case: true
    use-generated-keys: true
    default-executor-type: reuse
    defaultStatementTimeout: 1000
    jdbc-type-for-null: null
    call-setters-on-nulls: true
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://${eurekaUserName}:${eurekaPassWord}@localhost:9000/eureka/
  instance:
    status-page-url-path: /actuator/info
    health-check-url-path: /actuator/health
eurekaUserName: spark
eurekaPassWord: spark

management:
  metrics:
    web:
      server:
        auto-time-requests: false
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    bus-refresh:
      enabled: true

swagger:
  base-package: com.spark.platform.adminbiz
  enabled: true
  description: spark用户服务
  version: V1.0
  license: Apache License, Version 2.0
  license-url: https://www.apache.org/licenses/LICENSE-2.0.html
  authorization:
    key-name: Authorization
  contact:
    name: wangdingfeng
    email: wangdingfeng@live.com

security:
  oauth2:
    client:
      client-id: spark-admin
      client-secret: spark-admin-secret
    resource:
      jwt:
        key-value: spark_oauth_key

ribbon:
  ReadTimeout: 10000 #请求处理的超时时间
  ConnectTimeout: 5000 #请求连接的超时时间
  MaxAutoRetries: 1 #对当前实例的重试次数
  MaxAutoRetriesNextServer: 2 #切换实例的重试次数
  eureka:
    enabled: true

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000

#熔断器开启
feign:
  hystrix:
    enabled: true
  okhttp:
    enabled: true
  httpclient:
    enabled: false

# 直接放行URL
ignore:
  urls:
    - /actuator/**
    - /druid/**
    - /**/api/**
    - /v2/api-docs
    - /swagger-ui.html
    - /swagger-resources/**
    - /webjars/**
spark:
#  文件保存路径
  file-path: E:/spark/file