server:
  port: 9003
spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: spark-tx-manager
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url:  jdbc:mysql://mysql.example.com:3306/spark?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password:
    name: spark
    type: com.alibaba.druid.pool.DruidDataSource
    initial-size: 5
    min-idle: 5
    max-active: 20
    max-wait: 30000
    time-between-eviction-runs-millis: 60000
    min-evictable-idle-time-millis: 300000
    validation-query: select '1' from dual
    test-while-idle: true
    test-on-borrow: false
    test-on-return: false
    pool-prepared-statements: true
    max-open-prepared-statements: 20
    max-pool-prepared-statement-per-connection-size: 20
    filters: stat,wall
  boot:
    admin:
      client:
        url: http://127.0.0.1:9002
        instance:
          prefer-ip: true
          #          分服务器部署一定要配置ip
          service-url: http://127.0.0.1:9020
  redis:
    host: redis.example.com
    port: 6379
    timeout: 10000
    database: 0
    password:
    lettuce:
      pool:
        max-active: 30
        max-idle: 10
        max-wait: -1
        min-idle: 20
      shutdown-timeout: 10000
mybatis:
  configuration:
    map-underscore-to-camel-case: true
    use-generated-keys: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://${eurekaUserName}:${eurekaPassWord}@127.0.0.1:9000/eureka/
  instance:
    status-page-url-path: /actuator/info
    health-check-url-path: /actuator/health
    #      分服务器部署一定要配置ip
    prefer-ip-address: true
    ip-address: 127.0.0.1
eurekaUserName: spark
eurekaPassWord: spark

management:
  metrics:
    web:
      server:
        auto-time-requests: false
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    bus-refresh:
      enabled: true
# TxManager Host Ip
tx-lcn:
  manager:
    #TxManager Host Ip
    host: redis.example.com
    port: 8070
    #后台登录密码
    admin-key: 123456
    # 开启日志
  logger:
    enabled: true
logging:
  level:
    com:
      codingapi:
        txlcn: debug